---
- hosts: all
  become: true
  tasks:
    - name: Create user tom
      user:
        name: tom
        password: "{{ 'Vaibhi.1013!!' | password_hash('sha512') }}"
        groups: root
        append: yes

    - name: Add SSH key for tom
      authorized_key:
        user: tom
        state: present
        key: "{{ lookup('file', '/home/Avy/.ssh/ansible.pub') }}"

    - name: Allow 'tom' to have passwordless sudo
      copy:
        dest: /etc/sudoers.d/tom
        content: 'tom ALL=(ALL) NOPASSWD:ALL'
        mode: '0440'
  
- hosts: ansible
  become: true
  tasks:
  
  - name: ansible task
    yum:
      name:
        - nginx
        - httpd
      state: absent
      update_cache: yes


- hosts: web_server
  become: true
  tags: testing  
  tasks: 

  - name: installing apache on server
    yum:
      name:
        - httpd
      state: present
      update_cache: yes

  - name: copy task
    tags: copy
    copy:
      src: site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start httpd (Rhel)
    tags: apache, centos, httpd 
    service:
      name: httpd
      state: started
      

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
        
